### ISSUE TITLE
Problems loading Script into Addins

### ISSUE THREAD

**Issue by khcassidy** [sbobovyc/GameTools#5]
[import_pix.zip](https://github.com/sbobovyc/GameTools/files/420164/import_pix.zip)

Hello,
I have used RenderDoc to extract a model to CSV file.
I have been trying to load the import_pix.py script in to Blender. I have tried a fewof different Blender versions from the latest 2.7 to older 2.66 and 2.5 and I can not get he script loaded, it errors when I tick the box to enable it.

(Blender is running on Windows 10 I tried two different computers)
--------------/
Traceback (most recent call last):
  File "C:\blender-2.74-windows64\blender-2.74-windows64\2.74\scripts\modules\addon_utils.py", line 306, in enable
    mod = __import__(module_name)
  File "C:\Users\kcassidy\AppData\Roaming\Blender Foundation\Blender\2.74\scripts\addons\import_pix.py", line 240, in <module>
    bpy.ops.object.pix_csv_importer('INVOKE_DEFAULT')
  File "C:\blender-2.74-windows64\blender-2.74-windows64\2.74\scripts\modules\bpy\ops.py", line 183, in __call__
    BPyOpsSubModOp._scene_update(context)
  File "C:\blender-2.74-windows64\blender-2.74-windows64\2.74\scripts\modules\bpy\ops.py", line 149, in _scene_update
    scene = context.scene
AttributeError: '_RestrictContext' object has no attribute 'scene'
--------------/
I have attached a screen shot of the error.

Really appreciate
![blendererror](https://cloud.githubusercontent.com/assets/6579138/17697235/e57a1612-63b3-11e6-82ce-bb0dfd0f70d0.png)
 any pointers you could give.
Thanks.

**Comment by sbobovyc** [comment]
Can you give me the file you are trying to load?

**Comment by khcassidy** [comment]
Hi sbobovyc, import_pix.zip attached to the original post (at the top).

**Comment by sbobovyc** [comment]
Looks like whitespace formatting is messed up in the script file. Try downloading the script again and don't open it in any text editors.
